### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Signup a user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "johndoe@hotmail.com",
  "password": "pass-123"
}

### Signin a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "johndoe@hotmail.com",
  "password": "pass-123"
}

### Signout a user
POST http://localhost:3000/auth/signout

