### List all users
GET http://localhost:3000/users

### Get a user
GET http://localhost:3000/users/1

### Signup a user
POST http://localhost:3000/users/signup
content-type: application/json

{
  "email": "johndoe@hotmail.com",
  "password": "pass-123"
}

### Signin a user
POST http://localhost:3000/users/signin
content-type: application/json

{
  "email": "johndoe@hotmail.com",
  "password": "pass-1234"
}

### Update a user
PATCH http://localhost:3000/users/2
content-type: application/json

{
  "password": "pass-456"
}

### Delete a user
DELETE http://localhost:3000/users/3